### ISSUE TITLE
Collect as many workshops/minilectures/tracks possible and then advertise the event officially to find even more. :-)

### ISSUE THREAD

**Issue by boamaod** [okestonia/opendataday#1]
**If you have something to share then we'd like to hear from you and your experiences with creation or usage of open data. Just add a comment to this issue and include a short introduction about what you would like to do!**

We currently have:

* Tartu University library introduces Open Science and Scientific Data
* Nicola introduces linked data (what they are, how to search, etc.) and make your first Wikidata commit
* Wikimedia about using/reusing/uploading images from public databases/archives and using Wikidata for that
* Digital Humanities Association makes an example of data in humanities
* Märt about his experience developing https://opendata.riik.ee (see https://github.com/infoaed/opendata-portal for more) and data portals/challenges in our region (Antti from OK-FI might join for more detailed overview about Finland)

**Comment by boamaod** [comment]
We should also go through workshops and topics of last year and invite people to join for the next phase (see DOC/PDF at the bottom of the page):

* http://hub.garage48.org/tartu/blog/tartu-open-data-event

My personal next phase thing will be [Open Tartu](https://github.com/infoaed/opentartu) which started from "3. Budget expenditures and government decisions". If you know some people who were in those workgroups, you can contact them and ask (or invite adding their comments to this issue here). I also have somewhere list of e-mails of people who signed up for last years event, if you need some help finding contacts for people who were there last year (ask me).

**Comment by nvitucci** [comment]
@boamaod Maybe someone from the City Council whom you've spoken to in the past?

**Comment by nvitucci** [comment]
Does anyone know any people working at [Statistics Estonia](http://www.stat.ee)? Could they be interested?

**Comment by tkardi** [comment]
@nvitucci I asked around in the stat office if they'd be interested. And will contact the Estonian Land Board aswell.

**Comment by nvitucci** [comment]
Thanks @tkardi!

**Comment by tkardi** [comment]
Got an initial confirmation that Regio would like to give a talk about using open data in Regio's map production pipeline. Contact for further info: leida.lepik@regio.ee

**Comment by keeganmcbride** [comment]
I am able to give a talk on the Horizon2020 funded OpenGovIntelligence project (www.opengovintelligence.eu). In essence, the project aims to demonstrate how open data can change our understanding of public service delivery as well as how open data can be used to drive the coproduction of new services. 

The focus of the talk would be on the background of our project, drivers and barriers related to open data in Estonia, as well as how open data can be used to create new services.

**Comment by tkardi** [comment]
The Estonian Land Board has decided not to participate with a talk this year but somebody will be present to take back a positive experience for next time (so maybe a presentation / workshop next time ;)).

**Comment by nvitucci** [comment]
I updated the Web page with the venue, and I would like to finalize it with the talks we will give and a pseudo-definitive list of talks. For this, I need:

- the confirmation of the three partners as listed in #6 , #7 , and #5 ;
- a description of what @boamaod and @keeganmcbride will talk about (a couple lines should be enough, I'll also add mine);
- logos and names of both people and institutions (see #8).

Also, we should probably start thinking about a schedule in terms of time. How do you think? Only a few days are left, so we should do this ASAP.

**Comment by nvitucci** [comment]
@keeganmcbride Can I use the short description you already wrote ("In essence...")? What name should I use?

**Comment by keeganmcbride** [comment]
@nvitucci Unfortunately I am unable to participate as I have an MRI at Tartu Haigla at the same time, I had told @boamaod, but forgot to update here.

**Comment by nvitucci** [comment]
@keeganmcbride Oh, what a pity, that sounded really like an interesting talk! Maybe you can make a "quick appearance" in the afternoon since we'll stay until 16:00, or is it impossible?
